services:
  frontend:
    container_name: bolsa-front
    restart: unless-stopped
    image: bolsa-front:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${VITE_PORT}:80"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      api_network:
        ipv4_address: 172.19.0.5
networks:
  api_network:
      external: true
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 172.19.0.0/24